version: "3.2"

services:      
  who1:
    image: nginx
    networks:
      - rv_proxy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.backend=app1"
        - "traefik.frontend.rule=Host:app1.docki.me"
        - "traefik.port=80"
        - "traefik.docker.network=rv_proxy"
        - "traefik.backend.loadbalancer.method=wrr"
        - "traefik.backend.loadbalancer.swarm=true"        
networks:
  rv_proxy:
    external: true