version: "3.2"

services:

  traefik:
    image: traefik:1.5
    environment:
      - GODADDY_API_KEY=dLYoQpm22qLj_3knQXhkJCX2DoXfjCqbf3b
      - GODADDY_API_SECRET=3knSTKCzTRQxrkLvFx8UDK
    command:
      - --docker
      - --docker.swarmmode=true
      - --docker.domain=docki.me
      - --docker.watch=true
      - --docker.exposedbydefault=true
      - --docker.endpoint=unix:///var/run/docker.sock
      - --debug=true
      - --logLevel=WARN
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - rv_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/traefik/acme/acme.json:/etc/traefik/acme/acme.json
      - /etc/traefik/traefik_configs/traefik.toml:/etc/traefik/traefik.toml
      #- /etc/letsencrypt/live/docki.me/chain.pem:/etc/traefik/fullchain.pem
      #- /etc/letsencrypt/live/docki.me/cert.pem:/etc/traefik/cert.pem
    labels:
      - "traefik.enable=true"
      - "traefik.logLevel=DEBUG"
      - "traefik.port=8080"
      - "traefik.passHostHeader=true"
      - "traefik.frontend.entryPoints=https"    
      - "traefik.protocol=https"
      - "traefik.frontend.rule=Host:traefik.docki.me"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role==manager]
      restart_policy:
        condition: on-failure

networks:
  rv_proxy:
    external: true