version: '3.3'

services:
   db:
     image: mysql:5.7
     networks:
       - db_net
     volumes:
       - db_data:/var/lib/mysql        
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     networks:
       - rv_proxy
       - db_net
     deploy:
       labels:
        - "traefik.enable=true"
        - "traefik.backend=wordpress"
        - "traefik.frontend.rule=Host:word.docki.me"
        - "traefik.port=80"        
        - "traefik.docker.network=rv_proxy"
        - "traefik.backend.loadbalancer.method=wrr"
        - "traefik.backend.loadbalancer.swarm=true"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
volumes:
    db_data:
networks:
  rv_proxy:
    external: true
  db_net: